import { Platform, StyleSheet } from "react-native";

const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: "#FFFDF8" },
  app: { flex: 1 },
  scroll: { padding: 20, paddingBottom: 28 },
  authScreen: { flex: 1, backgroundColor: "#FFFDF8" },
  authContent: { padding: 24, paddingTop: 30, paddingBottom: 36 },
  authBrand: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "center",
    gap: 8,
    marginBottom: 42,
  },
  authLogo: { width: 48, height: 48 },
  authBrandText: {
    color: "#18362A",
    fontSize: 30,
    fontWeight: "800",
    letterSpacing: -1.2,
  },
  authEyebrow: {
    color: "#0D6A49",
    fontSize: 10,
    fontWeight: "900",
    letterSpacing: 1.4,
    marginBottom: 9,
  },
  authTitle: {
    color: "#1B3528",
    fontSize: 30,
    lineHeight: 35,
    fontWeight: "800",
    letterSpacing: -0.9,
  },
  authSubtitle: {
    color: "#718078",
    fontSize: 14,
    lineHeight: 20,
    marginTop: 8,
    marginBottom: 26,
  },
  authForm: { gap: 12 },
  authLabel: { color: "#304238", fontSize: 11, fontWeight: "800", marginBottom: 6 },
  authInputWrap: {
    minHeight: 53,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: "#E1E7DF",
    backgroundColor: "#FFFFFF",
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  authInput: { flex: 1, color: "#263A2F", fontSize: 14, paddingVertical: 0 },
  authError: { color: "#B83C38", fontSize: 12, lineHeight: 17, marginTop: -2 },
  authButton: {
    minHeight: 55,
    borderRadius: 16,
    backgroundColor: "#0D6A49",
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 8,
    marginTop: 5,
  },
  authButtonText: { color: "#FFFFFF", fontSize: 15, fontWeight: "800" },
  authDemoButton: {
    minHeight: 51,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: "#D5E7C7",
    backgroundColor: "#F2F8E9",
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 8,
    marginTop: 14,
  },
  authDemoText: { color: "#0D6A49", fontSize: 13, fontWeight: "800" },
  authIdeaButton: {
    minHeight: 49,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: "#F0DCA9",
    backgroundColor: "#FFF9EB",
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 8,
    marginTop: 9,
    paddingHorizontal: 14,
  },
  authIdeaButtonHover: {
    backgroundColor: "#FFF1C9",
    borderColor: "#E8C66F",
    transform: [{ translateY: -2 }],
  },
  authIdeaText: {
    color: "#936C13",
    fontSize: 12,
    fontWeight: "800",
  },
  authDivider: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginVertical: 24,
  },
  authDividerLine: { flex: 1, height: 1, backgroundColor: "#E8ECE5" },
  authDividerText: { color: "#99A39C", fontSize: 12, fontWeight: "700" },
  authFooterRow: { flexDirection: "row", justifyContent: "center", gap: 4 },
  authFooterText: { color: "#748078", fontSize: 12 },
  authLink: { color: "#0D6A49", fontSize: 12, fontWeight: "800" },
  authNote: { color: "#9AA49D", fontSize: 10, textAlign: "center", marginTop: 22 },
  authBack: { flexDirection: "row", alignItems: "center", gap: 7, marginBottom: 26 },
  authBackText: { color: "#0D6A49", fontSize: 12, fontWeight: "800" },
  onboardingScreen: { flex: 1, backgroundColor: "#FFFDF8", padding: 24 },
  onboardingTop: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  onboardingBrand: { flexDirection: "row", alignItems: "center", gap: 7 },
  onboardingLogo: { width: 36, height: 36 },
  onboardingBrandText: { color: "#18362A", fontSize: 23, fontWeight: "900" },
  onboardingSkip: { color: "#75847A", fontSize: 12, fontWeight: "800" },
  onboardingBody: { flex: 1, justifyContent: "center", alignItems: "center", paddingHorizontal: 10 },
  onboardingIcon: { width: 124, height: 124, borderRadius: 40, alignItems: "center", justifyContent: "center", marginBottom: 35 },
  onboardingEyebrow: { color: "#0D6A49", fontSize: 10, fontWeight: "900", letterSpacing: 1.5, textAlign: "center", marginBottom: 11 },
  onboardingTitle: { color: "#1B3528", fontSize: 31, lineHeight: 36, fontWeight: "900", textAlign: "center", letterSpacing: -0.8 },
  onboardingText: { color: "#718078", fontSize: 15, lineHeight: 22, textAlign: "center", marginTop: 12, maxWidth: 330 },
  onboardingBottom: { paddingBottom: 12 },
  onboardingDots: { flexDirection: "row", justifyContent: "center", gap: 7, marginBottom: 18 },
  onboardingDot: { width: 7, height: 7, borderRadius: 4, backgroundColor: "#DDE5DA" },
  onboardingDotActive: { width: 23, backgroundColor: "#0D6A49" },
  onboardingButton: { height: 54, borderRadius: 17, backgroundColor: "#0D6A49", alignItems: "center", justifyContent: "center", flexDirection: "row", gap: 8 },
  onboardingButtonPressed: { opacity: 0.82, transform: [{ scale: 0.99 }] },
  onboardingButtonText: { color: "#fff", fontSize: 15, fontWeight: "900" },
  screen: {
    flex: 1,
    backgroundColor: "#FFFDF8",
    paddingHorizontal: 20,
    paddingTop: 22,
  },
  top: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 27,
  },
  brand: { flexDirection: "row", alignItems: "center", gap: 8 },
  logo: {
    width: 43,
    height: 43,
  },
  brandText: {
    color: "#18362A",
    fontSize: 27,
    fontWeight: "800",
    letterSpacing: -1,
  },
  avatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#E9F2D5",
  },
  avatarText: { color: "#1B6246", fontSize: 12, fontWeight: "800" },
  hello: {
    color: "#19372B",
    fontSize: 26,
    fontWeight: "800",
    letterSpacing: -0.8,
  },
  subhello: { color: "#718078", fontSize: 15, marginTop: 4, marginBottom: 20 },
  hero: {
    minHeight: 221,
    borderRadius: 24,
    padding: 22,
    overflow: "hidden",
    marginBottom: 27,
  },
  glow: {
    position: "absolute",
    width: 155,
    height: 155,
    borderRadius: 80,
    right: -36,
    top: -28,
    backgroundColor: "rgba(233,246,213,0.12)",
  },
  eyebrow: {
    color: "#C4E7B9",
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 1.3,
    marginBottom: 9,
  },
  heroTitle: {
    color: "#fff",
    fontSize: 25,
    lineHeight: 30,
    fontWeight: "800",
    letterSpacing: -0.7,
    width: "76%",
  },
  heroText: { color: "#D7F0DC", fontSize: 13, marginTop: 9, lineHeight: 19 },
  leaf: {
    position: "absolute",
    top: 36,
    right: 25,
    width: 59,
    height: 59,
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(232,246,213,0.12)",
  },
  heroButton: {
    position: "absolute",
    bottom: 20,
    left: 22,
    height: 37,
    borderRadius: 18,
    paddingHorizontal: 14,
    flexDirection: "row",
    gap: 7,
    alignItems: "center",
    backgroundColor: "#E8F6D5",
  },
  heroButtonText: { color: "#0D6748", fontSize: 13, fontWeight: "800" },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 13,
  },
  sectionTitle: { color: "#1D3026", fontSize: 17, fontWeight: "800" },
  month: { color: "#849088", fontSize: 12, fontWeight: "600" },
  link: { color: "#0E6A49", fontSize: 13, fontWeight: "800" },
  metrics: { flexDirection: "row", gap: 9, marginBottom: 28 },
  metric: { flex: 1, minHeight: 101, borderRadius: 17, padding: 12 },
  metricNumber: {
    fontSize: 25,
    lineHeight: 30,
    fontWeight: "800",
    marginTop: 3,
  },
  metricText: {
    fontSize: 11,
    color: "#617068",
    fontWeight: "600",
    marginTop: 1,
  },
  card: {
    minHeight: 90,
    borderRadius: 18,
    paddingHorizontal: 13,
    paddingVertical: 12,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#EEF0EA",
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 10,
  },
  productIcon: {
    width: 52,
    height: 52,
    borderRadius: 16,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#F4F5EE",
    marginRight: 12,
    overflow: "hidden",
  },
  productImage: { width: "100%", height: "100%" },
  emoji: { fontSize: 25 },
  productName: {
    color: "#23372C",
    fontSize: 15,
    fontWeight: "800",
    marginBottom: 2,
  },
  meta: { color: "#77837C", fontSize: 11, marginBottom: 6 },
  pill: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 7,
    paddingVertical: 3,
    borderRadius: 10,
  },
  pillText: { fontSize: 10, fontWeight: "800" },
  mainButton: {
    marginTop: 6,
    minHeight: 54,
    borderRadius: 17,
    backgroundColor: "#0D6A49",
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 8,
  },
  mainButtonText: { color: "#fff", fontSize: 15, fontWeight: "800" },
  listHead: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 21,
  },
  title: {
    color: "#1C3327",
    fontSize: 27,
    fontWeight: "800",
    letterSpacing: -0.8,
  },
  subtitle: { color: "#748078", fontSize: 13, marginTop: 4 },
  plus: {
    width: 44,
    height: 44,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#0D6A49",
  },
  filters: { gap: 8, paddingBottom: 17 },
  chip: {
    height: 35,
    borderRadius: 18,
    paddingHorizontal: 13,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#E5E9E1",
    backgroundColor: "#fff",
  },
  chipActive: { backgroundColor: "#E9F6D5", borderColor: "#D5E9B7" },
  chipText: { color: "#6B766F", fontSize: 12, fontWeight: "700" },
  chipTextActive: { color: "#0D6A49" },
  list: { paddingBottom: 15 },
  empty: { paddingVertical: 32, alignItems: "center", gap: 9 },
  emptyText: { color: "#728078", fontSize: 13, textAlign: "center" },
  impact: {
    flexDirection: "row",
    gap: 13,
    padding: 16,
    borderRadius: 18,
    backgroundColor: "#E9F6D5",
    marginTop: 25,
  },
  impactIcon: {
    width: 42,
    height: 42,
    borderRadius: 14,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#D7EDC0",
  },
  impactTitle: { color: "#194C35", fontSize: 14, fontWeight: "800" },
  impactText: { color: "#4F7060", fontSize: 12, lineHeight: 17, marginTop: 3 },
  heading: {
    color: "#1E3228",
    fontSize: 17,
    fontWeight: "800",
    marginTop: 27,
    marginBottom: 12,
  },
  historyItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#EEF0EA",
  },
  historyIcon: {
    width: 39,
    height: 39,
    borderRadius: 13,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
  },
  historyProduct: { color: "#26382E", fontSize: 14, fontWeight: "800" },
  historyAction: { color: "#7B867F", fontSize: 11, marginTop: 2 },
  historyDate: { color: "#8B958E", fontSize: 11, fontWeight: "600" },
  profileTop: { alignItems: "center", paddingTop: 10, paddingBottom: 24 },
  bigAvatar: {
    width: 75,
    height: 75,
    borderRadius: 28,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#E8F0D7",
    marginBottom: 12,
  },
  bigAvatarText: { color: "#1A694A", fontSize: 21, fontWeight: "800" },
  profileName: { color: "#1B3427", fontSize: 21, fontWeight: "800" },
  profileBusiness: { color: "#77837C", fontSize: 13, marginTop: 4 },
  profileStats: {
    flexDirection: "row",
    paddingVertical: 16,
    backgroundColor: "#fff",
    borderColor: "#EDF0E9",
    borderWidth: 1,
    borderRadius: 18,
  },
  profileStat: {
    flex: 1,
    alignItems: "center",
    borderRightWidth: 1,
    borderRightColor: "#EEF0EA",
  },
  profileValue: { color: "#0E6A49", fontSize: 20, fontWeight: "800" },
  profileLabel: {
    color: "#7C877F",
    fontSize: 10,
    fontWeight: "600",
    marginTop: 3,
  },
  setting: {
    height: 61,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    backgroundColor: "#fff",
    borderRadius: 15,
    borderWidth: 1,
    borderColor: "#EEF0EA",
    marginBottom: 8,
  },
  settingIcon: {
    width: 34,
    height: 34,
    borderRadius: 11,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#EFF6E8",
    marginRight: 11,
  },
  settingText: { flex: 1, color: "#314036", fontSize: 13, fontWeight: "700" },
  settingRight: {
    color: "#278657",
    fontSize: 11,
    fontWeight: "700",
    marginRight: 5,
  },
  tip: {
    flexDirection: "row",
    gap: 10,
    padding: 15,
    borderRadius: 17,
    backgroundColor: "#FFF6DD",
    marginTop: 18,
    marginBottom: 18,
  },
  tipText: { flex: 1, color: "#7E641D", fontSize: 12, lineHeight: 17 },
  aboutBrand: { flexDirection: "row", alignItems: "center", gap: 13, padding: 16, borderRadius: 19, backgroundColor: "#E9F6D5", marginBottom: 18 },
  aboutLogo: { width: 55, height: 55 },
  aboutTitle: { color: "#1C4C35", fontSize: 22, fontWeight: "900" },
  aboutVersion: { color: "#5D826C", fontSize: 11, fontWeight: "800", marginTop: 2 },
  aboutCallout: { padding: 16, borderRadius: 17, backgroundColor: "#FFF6DD", marginTop: 8 },
  aboutCalloutTitle: { color: "#6F5718", fontSize: 13, fontWeight: "900" },
  aboutCalloutText: { color: "#806D38", fontSize: 12, lineHeight: 18, marginTop: 5 },
  tabs: {
    height: Platform.select({ ios: 77, default: 67 }),
    paddingBottom: Platform.select({ ios: 14, default: 7 }),
    paddingHorizontal: 8,
    backgroundColor: "#fff",
    borderTopWidth: 1,
    borderTopColor: "#ECF0E9",
    flexDirection: "row",
  },
  tab: { flex: 1, alignItems: "center", justifyContent: "center", gap: 3 },
  tabText: { color: "#8A958D", fontSize: 10, fontWeight: "700" },
  tabTextActive: { color: "#0D6A49" },
  modal: { flex: 1, backgroundColor: "#FFFDF8" },
  modalHead: {
    height: 65,
    paddingHorizontal: 20,
    borderBottomWidth: 1,
    borderBottomColor: "#EEF0EA",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  modalTitle: { color: "#203529", fontSize: 16, fontWeight: "800" },
  form: { padding: 20, paddingBottom: 45 },
  formIntro: { color: "#738078", fontSize: 14, marginBottom: 23 },
  inputWrap: { marginBottom: 17 },
  inputLabel: {
    color: "#304237",
    fontSize: 12,
    fontWeight: "800",
    marginBottom: 8,
  },
  input: {
    height: 50,
    borderWidth: 1,
    borderColor: "#E1E6DE",
    borderRadius: 14,
    paddingHorizontal: 14,
    backgroundColor: "#fff",
    color: "#1F3428",
    fontSize: 14,
  },
  categories: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 17,
  },
  category: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    paddingHorizontal: 10,
    height: 37,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#E3E8E0",
    backgroundColor: "#fff",
  },
  categoryActive: { borderColor: "#0E6A49", backgroundColor: "#EFF7E8" },
  categoryText: { color: "#647269", fontSize: 11, fontWeight: "700" },
  categoryTextActive: { color: "#0E6A49" },
  hint: { color: "#849088", fontSize: 11, marginTop: -10, marginBottom: 27 },
  datePresets: { flexDirection: "row", alignItems: "center", flexWrap: "wrap", gap: 7, marginTop: -12, marginBottom: 24 },
  datePresetLabel: { color: "#7B887F", fontSize: 10, fontWeight: "800", marginRight: 2 },
  datePreset: { borderRadius: 10, borderWidth: 1, borderColor: "#DDE8D6", backgroundColor: "#F4F9EE", paddingHorizontal: 9, paddingVertical: 6 },
  datePresetText: { color: "#27704F", fontSize: 10, fontWeight: "800" },
  save: {
    height: 55,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 8,
    backgroundColor: "#0D6A49",
  },
  saveText: { color: "#fff", fontSize: 15, fontWeight: "800" },
  detail: { padding: 20, paddingBottom: 42 },
  detailTop: { alignItems: "center", paddingTop: 5, paddingBottom: 24 },
  detailIcon: {
    width: 83,
    height: 83,
    borderRadius: 26,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#F1F4EB",
    marginBottom: 13,
    overflow: "hidden",
  },
  detailImage: { width: "100%", height: "100%" },
  detailEmoji: { fontSize: 42 },
  detailName: {
    color: "#1B3528",
    fontSize: 23,
    fontWeight: "800",
    textAlign: "center",
  },
  detailMeta: { color: "#7B867E", fontSize: 13, marginTop: 5 },
  detailPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 14,
    marginTop: 13,
  },
  detailPillText: { fontSize: 12, fontWeight: "800" },
  advice: {
    flexDirection: "row",
    gap: 12,
    padding: 15,
    borderRadius: 18,
    backgroundColor: "#E9F6D5",
  },
  adviceIcon: {
    height: 39,
    width: 39,
    borderRadius: 13,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#D5EBB9",
  },
  adviceTitle: { color: "#24513B", fontSize: 13, fontWeight: "800" },
  adviceText: { color: "#52715F", fontSize: 12, lineHeight: 17, marginTop: 3 },
  actionTitle: {
    color: "#22382C",
    fontSize: 16,
    fontWeight: "800",
    marginTop: 27,
    marginBottom: 10,
  },
  action: {
    minHeight: 67,
    borderRadius: 16,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: "#EAEDE7",
    backgroundColor: "#fff",
    flexDirection: "row",
    alignItems: "center",
    gap: 11,
    marginBottom: 9,
  },
  actionIcon: {
    height: 39,
    width: 39,
    borderRadius: 13,
    alignItems: "center",
    justifyContent: "center",
  },
  actionLabel: { color: "#2A3E31", fontSize: 13, fontWeight: "800" },
  actionSub: { color: "#859087", fontSize: 10, marginTop: 2 },
  delete: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingTop: 22,
  },
  deleteText: { color: "#BC3D38", fontSize: 12, fontWeight: "800" },
  quickGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginBottom: 28,
  },
  quickCard: {
    width: "48%",
    minHeight: 142,
    padding: 14,
    borderRadius: 18,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E9EDE7",
  },
  quickIcon: {
    width: 38,
    height: 38,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 10,
  },
  quickTitle: { color: "#253A2E", fontSize: 14, fontWeight: "800" },
  quickText: { color: "#7B867F", fontSize: 10, marginTop: 3, marginBottom: 9 },
  impactSummary: { padding: 16, borderRadius: 19, backgroundColor: "#E9F6D5", marginBottom: 27 },
  impactSummaryHead: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start" },
  impactSummaryEyebrow: { color: "#4F8064", fontSize: 9, fontWeight: "900", letterSpacing: 1.1 },
  impactSummaryTitle: { color: "#194C35", fontSize: 16, fontWeight: "900", marginTop: 4 },
  impactSummaryBadge: { minWidth: 45, height: 35, borderRadius: 13, alignItems: "center", justifyContent: "center", backgroundColor: "#D3EABA" },
  impactSummaryBadgeText: { color: "#1E704B", fontSize: 13, fontWeight: "900" },
  impactSummaryText: { color: "#52715F", fontSize: 11, lineHeight: 16, marginTop: 8 },
  impactProgressTrack: { height: 7, borderRadius: 5, backgroundColor: "#D3EABA", overflow: "hidden", marginTop: 12 },
  impactProgressFill: { height: "100%", borderRadius: 5, backgroundColor: "#278657" },
  subScreenHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginBottom: 24,
  },
  backButton: {
    width: 42,
    height: 42,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#E9F6D5",
  },
  subScreenTitle: { color: "#1C3327", fontSize: 23, fontWeight: "800" },
  subScreenSubtitle: { color: "#748078", fontSize: 11, marginTop: 2 },
  noticeCard: {
    minHeight: 76,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    padding: 15,
    borderRadius: 18,
  },
  noticeTitle: { color: "#2A3E31", fontSize: 13, fontWeight: "800" },
  noticeText: { color: "#68766D", fontSize: 11, lineHeight: 16, marginTop: 3 },
  opportunityHero: {
    padding: 18,
    borderRadius: 20,
    backgroundColor: "#FFF6DD",
  },
  opportunityHeroTitle: {
    color: "#6F5718",
    fontSize: 17,
    fontWeight: "800",
    marginTop: 9,
  },
  opportunityHeroText: {
    color: "#806D38",
    fontSize: 11,
    lineHeight: 17,
    marginTop: 5,
  },
  opportunityCard: {
    minHeight: 91,
    borderRadius: 18,
    padding: 13,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#ECEFE9",
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 10,
  },
  recommendation: { fontSize: 11, fontWeight: "800", marginTop: 5 },
  reportGrid: { flexDirection: "row", flexWrap: "wrap", gap: 10 },
  reportCard: {
    width: "48%",
    minHeight: 119,
    padding: 15,
    borderRadius: 18,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E9EDE7",
  },
  reportValue: {
    color: "#1E382B",
    fontSize: 25,
    fontWeight: "800",
    marginTop: 8,
  },
  reportLabel: { color: "#78837C", fontSize: 10, marginTop: 2 },
  chartCard: {
    padding: 17,
    borderRadius: 18,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E9EDE7",
  },
  chartRow: { marginBottom: 15 },
  chartLabels: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 7,
  },
  chartName: { color: "#34463B", fontSize: 12, fontWeight: "700" },
  chartTotal: { color: "#0D6A49", fontSize: 12, fontWeight: "800" },
  chartTrack: {
    height: 8,
    borderRadius: 4,
    backgroundColor: "#EDF1EB",
    overflow: "hidden",
  },
  chartBar: { height: 8, borderRadius: 4, backgroundColor: "#2D946A" },
  impactHero: {
    alignItems: "center",
    padding: 22,
    borderRadius: 22,
    backgroundColor: "#E9F6D5",
  },
  impactHeroValue: { color: "#0D6A49", fontSize: 42, fontWeight: "900" },
  impactHeroTitle: { color: "#244B37", fontSize: 15, fontWeight: "800" },
  impactHeroText: {
    color: "#627669",
    fontSize: 11,
    textAlign: "center",
    marginTop: 5,
  },
  impactStats: { flexDirection: "row", gap: 9, marginTop: 12 },
  impactStat: {
    flex: 1,
    alignItems: "center",
    paddingVertical: 13,
    borderRadius: 16,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#ECEFE9",
  },
  impactStatValue: {
    color: "#263A2F",
    fontSize: 20,
    fontWeight: "800",
    marginTop: 4,
  },
  impactStatLabel: { color: "#7E8881", fontSize: 9, marginTop: 1 },
  impactTimeline: {
    minHeight: 58,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#EDF0EA",
  },
  timelineDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: "#2D946A",
  },
  showcaseScreen: { flex: 1, backgroundColor: "#FFFDF8" },
  showcaseTopbar: {
    minHeight: 64,
    paddingHorizontal: 20,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderBottomWidth: 1,
    borderBottomColor: "#EEF1EA",
    backgroundColor: "rgba(255,253,248,0.96)",
  },
  showcaseBack: {
    minHeight: 36,
    paddingHorizontal: 8,
    borderRadius: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  showcaseBackHover: { backgroundColor: "#E9F6D5" },
  showcaseBackText: { color: "#0D6A49", fontSize: 12, fontWeight: "800" },
  showcaseMiniBrand: { flexDirection: "row", alignItems: "center", gap: 5 },
  showcaseMiniLogo: { width: 29, height: 29 },
  showcaseMiniBrandText: { color: "#18362A", fontSize: 20, fontWeight: "800" },
  showcaseLoginLink: { paddingHorizontal: 9, paddingVertical: 8 },
  showcaseLoginLinkText: { color: "#0D6A49", fontSize: 12, fontWeight: "800" },
  showcaseContent: { padding: 20, paddingTop: 0, paddingBottom: 36 },
  showcaseNav: { gap: 8, paddingVertical: 14 },
  showcaseNavItem: {
    paddingHorizontal: 13,
    paddingVertical: 8,
    borderRadius: 15,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E7ECE4",
  },
  showcaseNavItemHover: { backgroundColor: "#E9F6D5", borderColor: "#CFE6B8" },
  showcaseNavText: { color: "#506158", fontSize: 11, fontWeight: "800" },
  showcaseHero: {
    minHeight: 318,
    borderRadius: 26,
    padding: 23,
    overflow: "hidden",
    position: "relative",
  },
  showcaseHeroGlow: {
    position: "absolute",
    width: 245,
    height: 245,
    borderRadius: 125,
    right: -72,
    top: -74,
    backgroundColor: "rgba(233,246,213,0.13)",
  },
  showcaseHeroEyebrow: { color: "#C8E8BE", fontSize: 10, fontWeight: "900", letterSpacing: 1.5 },
  showcaseHeroTitle: {
    color: "#FFFFFF",
    fontSize: 30,
    lineHeight: 34,
    fontWeight: "900",
    letterSpacing: -0.9,
    marginTop: 11,
    width: "73%",
  },
  showcaseHeroText: { color: "#D8F0D9", fontSize: 13, lineHeight: 19, marginTop: 12, width: "74%" },
  showcaseHeroActions: { position: "absolute", left: 23, bottom: 21 },
  showcasePrimaryButton: {
    minHeight: 42,
    paddingHorizontal: 15,
    borderRadius: 21,
    backgroundColor: "#E9F6D5",
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 8,
  },
  showcasePrimaryButtonHover: { backgroundColor: "#FFFFFF", transform: [{ translateY: -2 }] },
  showcasePrimaryButtonText: { color: "#0D6748", fontSize: 12, fontWeight: "900" },
  showcaseHeroHint: { color: "#B9DFC1", fontSize: 10, marginTop: 8 },
  showcaseHeroMark: {
    position: "absolute",
    right: 6,
    top: 82,
    width: 145,
    height: 160,
    justifyContent: "center",
    alignItems: "center",
  },
  showcaseHeroLogo: { width: 145, height: 160 },
  showcaseIntroRow: { flexDirection: "row", gap: 12, alignItems: "center", paddingTop: 28 },
  showcaseIntroCopy: { flex: 1 },
  showcaseIntroTitle: { color: "#1E382B", fontSize: 21, lineHeight: 25, fontWeight: "900", marginBottom: 8 },
  showcasePhotoStack: { width: 125, height: 140, position: "relative" },
  showcasePhotoMain: { width: 101, height: 117, borderRadius: 20, position: "absolute", left: 0, top: 0 },
  showcasePhotoSmall: {
    width: 68,
    height: 68,
    borderRadius: 18,
    position: "absolute",
    right: 0,
    bottom: 0,
    borderWidth: 4,
    borderColor: "#FFFDF8",
  },
  showcaseSection: { marginTop: 38 },
  showcaseSectionTitle: { marginBottom: 17 },
  showcaseEyebrow: { color: "#0D6A49", fontSize: 10, fontWeight: "900", letterSpacing: 1.3, marginBottom: 7 },
  showcaseSectionHeading: { color: "#1E382B", fontSize: 24, lineHeight: 29, fontWeight: "900", letterSpacing: -0.5 },
  showcaseSectionText: { color: "#718078", fontSize: 13, lineHeight: 19, marginTop: 7 },
  showcaseSteps: { gap: 9 },
  showcaseStepCard: {
    padding: 14,
    borderRadius: 18,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E9EDE7",
  },
  showcaseStepTop: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  showcaseStepNumber: { color: "#A8B5AC", fontSize: 12, fontWeight: "900", letterSpacing: 1 },
  showcaseIconBox: { width: 39, height: 39, borderRadius: 13, alignItems: "center", justifyContent: "center" },
  showcaseStepTitle: { color: "#2B4033", fontSize: 15, fontWeight: "900", marginTop: 8 },
  showcaseStepText: { color: "#78847C", fontSize: 11, lineHeight: 16, marginTop: 3 },
  showcaseFeatureBand: {
    marginTop: 38,
    padding: 18,
    borderRadius: 23,
    backgroundColor: "#0D6A49",
    overflow: "hidden",
  },
  showcaseFeatureBandCopy: { paddingRight: 4 },
  showcaseFeatureBandTitle: { color: "#FFFFFF", fontSize: 22, lineHeight: 27, fontWeight: "900" },
  showcaseFeatureBandText: { color: "#D7F0DC", fontSize: 12, lineHeight: 18, marginTop: 8 },
  showcaseAudienceList: { gap: 8, marginTop: 16 },
  showcaseAudienceItem: { flexDirection: "row", alignItems: "center", gap: 8 },
  showcaseAudienceText: { color: "#F1F9E9", fontSize: 12, fontWeight: "700" },
  showcaseProductStrip: { flexDirection: "row", gap: 8, marginTop: 18 },
  showcaseStripPhoto: { flex: 1, height: 83, borderRadius: 16, opacity: 0.94 },
  showcasePlans: { gap: 11 },
  showcasePlanCard: {
    padding: 17,
    borderRadius: 20,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E8EDE5",
  },
  showcasePlanCardPro: { backgroundColor: "#FFF9EB", borderColor: "#F2DCAC" },
  showcaseProBadge: { alignSelf: "flex-start", borderRadius: 9, paddingHorizontal: 8, paddingVertical: 4, backgroundColor: "#F9D899", marginBottom: 11 },
  showcaseProBadgeText: { color: "#765514", fontSize: 9, fontWeight: "900", letterSpacing: 0.6 },
  showcasePlanHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  showcasePlanName: { color: "#203A2C", fontSize: 16, fontWeight: "900" },
  showcasePlanPrice: { color: "#0D6A49", fontSize: 11, fontWeight: "900" },
  showcasePlanDescription: { color: "#7A867E", fontSize: 11, lineHeight: 16, marginTop: 6, marginBottom: 12 },
  showcasePlanItem: { flexDirection: "row", alignItems: "center", gap: 7, marginTop: 7 },
  showcasePlanItemText: { color: "#4C5D53", fontSize: 11, flex: 1 },
  showcaseImpactRow: { flexDirection: "row", alignItems: "center", gap: 11, marginTop: 20, padding: 15, borderRadius: 18, backgroundColor: "#E9F6D5" },
  showcaseImpactTitle: { color: "#24513B", fontSize: 13, fontWeight: "900" },
  showcaseImpactText: { color: "#52715F", fontSize: 11, lineHeight: 16, marginTop: 3 },
  showcaseCheckpointList: { gap: 9 },
  showcaseCheckpoint: { flexDirection: "row", alignItems: "center", gap: 11, padding: 13, borderRadius: 17, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#E8EDE6" },
  showcaseCheckpointTag: { width: 47, height: 47, borderRadius: 15, alignItems: "center", justifyContent: "center", backgroundColor: "#E9F6D5" },
  showcaseCheckpointTagText: { color: "#0D6A49", fontSize: 13, fontWeight: "900" },
  showcaseCheckpointTitle: { color: "#2B4033", fontSize: 13, fontWeight: "900" },
  showcaseCheckpointText: { color: "#7B877F", fontSize: 10, lineHeight: 15, marginTop: 3 },
  showcaseCta: { marginTop: 38, padding: 20, borderRadius: 22, alignItems: "center", backgroundColor: "#FFF0E8" },
  showcaseCtaTitle: { color: "#5D3A27", fontSize: 20, lineHeight: 24, fontWeight: "900", textAlign: "center" },
  showcaseCtaText: { color: "#866553", fontSize: 12, lineHeight: 17, textAlign: "center", marginTop: 6 },
  showcaseCtaButton: { minHeight: 45, paddingHorizontal: 16, borderRadius: 22, flexDirection: "row", alignItems: "center", gap: 8, backgroundColor: "#E9F6D5", marginTop: 15 },
  showcaseCtaButtonHover: { backgroundColor: "#FFFFFF", transform: [{ translateY: -2 }] },
  showcaseCtaButtonText: { color: "#0D6748", fontSize: 12, fontWeight: "900" },
  showcaseFooter: { color: "#9AA49D", fontSize: 10, textAlign: "center", marginTop: 21 },
});

export default styles;
