import {
  Activity,
  Apple,
  ArrowLeft,
  ArrowLeftRight,
  ArrowRight,
  Bell,
  Box,
  Building2,
  CalendarDays,
  ChartNoAxesColumn,
  Check,
  ChevronRight,
  CircleAlert,
  CircleCheck,
  CircleHelp,
  CirclePlus,
  CircleX,
  Clock3,
  CloudOff,
  Code2,
  Coffee,
  Droplets,
  FileText,
  Flame,
  Funnel,
  Heart,
  House,
  Layers,
  Leaf,
  Lightbulb,
  Lock,
  LogOut,
  Mail,
  Map,
  MapPin,
  Moon,
  Navigation,
  Palette,
  Pencil,
  Plus,
  Rocket,
  RotateCcw,
  Search,
  ShoppingBasket,
  Sparkles,
  Store,
  Sun,
  Tag,
  Trash2,
  Type,
  User,
  Utensils,
  X,
} from "lucide-react-native";

const icons = {
  add: Plus,
  "add-circle": CirclePlus,
  "add-circle-outline": CirclePlus,
  "alert-circle-outline": CircleAlert,
  "analytics-outline": ChartNoAxesColumn,
  "arrow-back": ArrowLeft,
  "arrow-forward": ArrowRight,
  "bar-chart-outline": ChartNoAxesColumn,
  "basket-outline": ShoppingBasket,
  "bulb-outline": Lightbulb,
  "business-outline": Building2,
  "cafe-outline": Coffee,
  "calendar-outline": CalendarDays,
  calendar: CalendarDays,
  checkmark: Check,
  "checkmark-circle": CircleCheck,
  "checkmark-circle-outline": CircleCheck,
  "chevron-forward": ChevronRight,
  close: X,
  "close-circle": CircleX,
  "cloud-offline-outline": CloudOff,
  "code-slash-outline": Code2,
  "color-palette-outline": Palette,
  "create-outline": Pencil,
  cube: Box,
  "cube-outline": Box,
  "document-text-outline": FileText,
  "flame-outline": Flame,
  "funnel-outline": Funnel,
  "heart-outline": Heart,
  home: House,
  "home-outline": House,
  "help-circle-outline": CircleHelp,
  "information-circle-outline": CircleHelp,
  "layers-outline": Layers,
  leaf: Leaf,
  "leaf-outline": Leaf,
  "lock-closed-outline": Lock,
  "log-out-outline": LogOut,
  "mail-outline": Mail,
  "map-outline": Map,
  "location-outline": MapPin,
  "moon-outline": Moon,
  "navigate-outline": Navigation,
  "notifications-outline": Bell,
  "nutrition-outline": Apple,
  person: User,
  "person-outline": User,
  "pricetag-outline": Tag,
  pulse: Activity,
  "pulse-outline": Activity,
  "refresh-outline": RotateCcw,
  "restaurant-outline": Utensils,
  "rocket-outline": Rocket,
  search: Search,
  "search-outline": Search,
  sparkles: Sparkles,
  "sparkles-outline": Sparkles,
  "storefront-outline": Store,
  "sunny-outline": Sun,
  "swap-horizontal-outline": ArrowLeftRight,
  "text-outline": Type,
  "time-outline": Clock3,
  "trash-outline": Trash2,
  "water-outline": Droplets,
};

/**
 * Centraliza os ícones do Giro em vetores SVG do Lucide.
 * Os nomes antigos foram mantidos para preservar os dados e a estrutura das telas.
 */
export default function AppIcon({ name, size = 24, color = "#0D6A49", strokeWidth = 2, ...props }) {
  const Icon = icons[name] || CircleHelp;

  return <Icon size={size} color={color} strokeWidth={strokeWidth} {...props} />;
}
